export const weekDays = {
  ru: {
    long: [
      "воскресенье",
      "понедельник",
      "вторник",
      "среда",
      "четверг",
      "пятница",
      "суббота",
    ],
    short: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
  },
  en: {
    long: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    short: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
  },
};

export const months = {
  ru: {
    long: [
      "января",
      "февраля",
      "марта",
      "апреля",
      "мая",
      "июня",
      "июля",
      "сентября",
      "октября",
      "ноября",
      "декабря",
    ],
    short: [
      "янв.",
      "февр.",
      "апр.",
      "марта",
      "мая",
      "июня",
      "июля",
      "сент.",
      "окт.",
      "нояб.",
      "дек.",
    ],
  },
  en: {
    long: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    short: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
  },
};
